version: '3.8'

services:
  api:
    build: .
    image: my_fastapi_app
    container_name: fastapi_container
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"


